### ISSUE TITLE
Topology Operator container crash-looping after apply/delete of a bad Binding resource.

### ISSUE THREAD

**Issue by twhite0** [rabbitmq/messaging-topology-operator#196] opened 2021-07-27 12:56 UTC
## Describe the bug
I applied a Binding resource to my OpenShift cluster which had the spec of a Policy resource (copy/paste gone bad).  Upon attempting to delete the Binding resource the Operator container failed and went into a crash-loop.  I was only able to clean things up by patching the bad Binding resource prior to the reconciliation process kicking in.

## To Reproduce
1. Apply a bad Binding resource.  

The following file was applied to my namespace to kickstart the failure
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: test-failure
spec:
  name: test-failure
  rabbitmqClusterReference:
    name: psa-rabbit
---
#
# Do not use/copy.
# The following is a Policy definition with an incorrect kind (Binding)
# For testing purposes only.
#
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: test-failure
spec:
  name: test-failure
  vhost: test-failure
  applyTo: queues
  pattern: "target"
  definition:
    dead-letter-exchange: deadletter
    max-length: 2
  rabbitmqClusterReference:
    name: psa-rabbit
```

At this point the operator container is logging error messages that it cannot reconcile the Binding resource.
```
2021-07-27T12:24:16.071Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"Binding","namespace":"psa-dev","name":"test-failure","uid":"65447498-6ad6-4b4f-af5c-5b6e7caabd77","apiVersion":"rabbitmq.com/v1beta1","resourceVersion":"474583545"}, "reason": "FailedDeclare", "message": "failed to declare binding"}
2021-07-27T12:24:16.079Z	ERROR	controller-runtime.manager.controller.binding	Reconciler error	{"reconciler group": "rabbitmq.com", "reconciler kind": "Binding", "name": "test-failure", "namespace": "psa-dev", "error": "Error 405 (Error 405 from RabbitMQ: EOF): "}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
```

2. Attempt to delete the bad Binding resource.

Upon deleting the Binding resource, the failure cycle begins.
```
2021-07-27T12:26:48.106Z	INFO	controller-runtime.manager.controller.binding	Deleting	{"reconciler group": "rabbitmq.com", "reconciler kind": "Binding", "name": "test-failure", "namespace": "psa-dev"}
panic: runtime error: index out of range [0] with length 0

goroutine 852 [running]:
github.com/michaelklishin/rabbit-hole/v2.(*Client).DeleteBinding(0xc001ab73e0, 0xc007bf56f0, 0xc, 0x0, 0x0, 0xc007bf56f0, 0xc, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.10.0/bindings.go:218 +0x3f7
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).deleteBinding(0xc0006639c0, 0x1aa4798, 0xc007a3e540, 0x1abfba8, 0xc001ab73e0, 0xc002538340, 0x1abfba8, 0xc001ab73e0)
	/workspace/controllers/binding_controller.go:176 +0x198
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).Reconcile(0xc0006639c0, 0x1aa4798, 0xc007a3e540, 0xc007bf5699, 0x7, 0xc007bf5684, 0xc, 0xc007a3e540, 0xc000030000, 0x16fe2c0, ...)
	/workspace/controllers/binding_controller.go:87 +0x110b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001f0dc0, 0x1aa46f0, 0xc0003f2000, 0x16c30c0, 0xc0079ed640)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001f0dc0, 0x1aa46f0, 0xc0003f2000, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0073c2c10, 0xc0001f0dc0, 0x1aa46f0, 0xc0003f2000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:210 +0x425
```

3. Observe the failure and crash-loop.

At this point the restarting container hits the Binding resource and panics...rinse, repeat.
```
...
...
panic: runtime error: index out of range [0] with length 0

goroutine 836 [running]:
github.com/michaelklishin/rabbit-hole/v2.(*Client).DeleteBinding(0xc0002dea20, 0xc004a274f0, 0xc, 0x0, 0x0, 0xc004a274f0, 0xc, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/michaelklishin/rabbit-hole/v2@v2.10.0/bindings.go:218 +0x3f7
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).deleteBinding(0xc0006d8a00, 0x1aa4798, 0xc00487a3f0, 0x1abfba8, 0xc0002dea20, 0xc004e46680, 0x1abfba8, 0xc0002dea20)
	/workspace/controllers/binding_controller.go:176 +0x198
github.com/rabbitmq/messaging-topology-operator/controllers.(*BindingReconciler).Reconcile(0xc0006d8a00, 0x1aa4798, 0xc00487a3f0, 0xc004a274a9, 0x7, 0xc004a27494, 0xc, 0xc00487a3f0, 0xc000030000, 0x16fe2c0, ...)
	/workspace/controllers/binding_controller.go:87 +0x110b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00039b360, 0x1aa46f0, 0xc0002f0000, 0x16c30c0, 0xc00096aa80)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00039b360, 0x1aa46f0, 0xc0002f0000, 0xc0006b7700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc004782010, 0xc00039b360, 0x1aa46f0, 0xc0002f0000)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:210 +0x425
```

4. Workaround:  Patch the delete during container _startup_

I've been able to patch resources that have not been fully created/deleted, however in this case there was a timing challenge.  If not performed at the proper stage of the crash-loop the patch would fail.

```
$ oc patch binding.rabbitmq.com/test-failure -p '{"metadata":{"finalizers":[]}}' --type=merge
Error from server (InternalError): Internal error occurred: failed calling webhook "vbinding.kb.io": Post "https://webhook-service.rabbit-mq-poc.svc:443/validate-rabbitmq-com-v1beta1-binding?timeout=10s": no endpoints available for service "webhook-service"
```

I needed to watch the operator logs and catch it during the container startup and prior to going through the recon processing.  In my case the certificate watcher startup took a bit of time.  

```
2021-07-27T12:34:32.271Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2021-07-27T12:34:32.271Z	INFO	controller-runtime.webhook	serving webhook server	{"host": "", "port": 9443}
2021-07-27T12:34:32.271Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
```

At this point I could _sneak_ in a patch in which allowed me to delete the bad resource and stop the container crash-loop.

```
$ oc patch binding.rabbitmq.com/test-failure -p '{"metadata":{"finalizers":[]}}' --type=merge
binding.rabbitmq.com/test-failure patched
```

**Expected behavior**
The initial apply was clearly user error.  The Binding resource was not properly defined.  The crash-loop will need some investigation.

I've seen a couple cases where resources have failed to be created and then transition into a _zombie_ like state where they simply cannot be deleted due to not being fully created.  

## Version and environment information
- Messaging Topology Operator: **rabbitmqoperator/messaging-topology-operator:0.10.0**
- RabbitMQ: **rabbitmq:3.8.18-management**
- RabbitMQ Cluster Operator: **rabbitmqoperator/cluster-operator:1.8.0**
- Kubernetes: **v1.19.0+a5a0987**
- Cloud provider or hardware configuration: **OpenShift 4.6.26**

**Comment by ChunyiLyu** [comment] 2021-07-29 10:06
Hi @twhite0, thanks for using the operator! How did you manage to create the binding in the first place? There are CRD validation and defaults for `bindings.rabbitmq.com` to make sure that necessary fields are provided (see: https://github.com/rabbitmq/messaging-topology-operator/blob/main/api/v1beta1/binding_types.go#L19).  

When I tried creating the `test-failure` binding, this is the failure I got from `kubectl apply`

```bash
❯ kubectl apply -f binding
error: error validating "binding": error validating data: [ValidationError(Binding.spec): unknown field "applyTo" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "definition" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "name" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "pattern" in com.rabbitmq.v1beta1.Binding.spec]; if you choose to ignore these errors, turn validation off with --validate=false
```

Did you turn off validation? If you turn off CRD schema validation, you run the risk of not allowing schema validation to perform and therefore supply invalid object to the operator that it cannot reconcile. Does this have anything to do with the openshift cli `oc` you are using?

**Comment by twhite0** [comment] 2021-07-29 11:08
Hi @ChunyiLyu:  
> Did you turn off validation?

I've not purposefully turned off schema validation.  How would one go about doing this so I can check.  

> Does this have anything to do with the openshift cli oc you are using?

I'll try the same procedures to reproduce the issue with `kubectl`.

**Comment by twhite0** [comment] 2021-07-29 11:25
I tried a quick test using an older `kubectl` (v1.18) but your cli thought looks to be spot on.

```
$ kubectl apply -f test.yaml
error: error validating "test.yaml": error validating data: [ValidationError(Binding.spec): unknown field "applyTo" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "definition" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "name" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "pattern" in com.rabbitmq.v1beta1.Binding.spec]; if you choose to ignore these errors, turn validation off with --validate=false

$ oc apply -f test.yaml
vhost.rabbitmq.com/test-failure created
binding.rabbitmq.com/test-failure created
```

I'll dig around a bit to uncover why differences exist.

**Comment by twhite0** [comment] 2021-07-29 12:20
There is an annoyingly simple answer for the differences....the oc-cli has validation turned off by default, while with kubectl its on.

I can recreate the client side error messages by adding validation to my oc.  The `oc/kubectl apply help` identifies the same.

```
$ kubectl apply -f test.yaml
error: error validating "test.yaml": error validating data: [ValidationError(Binding.spec): unknown field "applyTo" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknoidationError(Binding.spec): unknown field "name" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "pattern" in com.rabbitmq.v1beta1.Binding.spec]; if you che=false

$ oc apply -f test.yaml --validate=true
vhost.rabbitmq.com/test-failure created
error: error validating "test.yaml": error validating data: [ValidationError(Binding.spec): unknown field "applyTo" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "definition" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "name" in com.rabbitmq.v1beta1.Binding.spec, ValidationError(Binding.spec): unknown field "pattern" in com.rabbitmq.v1beta1.Binding.spec]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by ChunyiLyu** [comment] 2021-07-30 09:14
@twhite0 😨 It's shocking to me that the openshift cli has validation turned off by default. I would suggest to keep the validation on for all usage (not just for using the Topology Operator) If there's no further question, I will close this issue for now since it's not not a bug in the operator.

**Closed** 2021-08-31 11:26 UTC
Labels: openshift
